# Branch whitelist
branches:
  only:
    - master
# Caching of bower_components & node_modules disabled, due to an increase in delayed breakages
cache:
  npm: false
  directories: null
dist: trusty
language: node_js
node_js:
  - 12
os: linux
